sudo: required
services: 
  - docker

before_install: 
  - docker build -t gnana03/docker-react -f Dockerfile.dev .

script: 
  - docker run gnana03/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-874106750687"
  buckt_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY" 
